### PR TITLE
Readthedocs

### PR DESCRIPTION
**Pull request by kritim13**
Documentation for ReadTheTocs for all modules except da_rnn.  Working on fixing the bug  for da_rnn currently.

### CODE REVIEW

**Comment by isaacmg** [comment]
Could you please  into the the merge conflicts? If you need help DM me on Slack.

**Comment by kritim13** [comment]
Sure, will do.

**Comment by isaacmg** [comment]
Think I fixed the merge conflicts but will check.

**Comment by isaacmg** [comment]
Could you fix the linting problems? Otherwise that will constantly raise an error until they are fixed due to Flake8 reqs. Thanks.

**Comment by kritimahajan13** [comment]
Great, apologies for not being able to get to this in time.

**Comment by kritim13** [comment]
Yes, on it now.

**Pull request merged**
