### PR TITLE
Transformer update

### PR DESCRIPTION
**Pull request by theadammurphy**
- Removed an unnecessary if/else block
- Added a docstring for the SimpleTransformer class in Sphinx style. Not all params have descriptions as I wasn't sure what some of them did.

### CODE REVIEW

**Review by isaacmg — CHANGES_REQUESTED** [review]
Thanks for the PR. Please fix the linting errors caused by the lines being too long https://app.circleci.com/pipelines/github/AIStream-Peelout/flow-forecast/3150/workflows/6d4b15aa-334d-4c45-904e-b27dcd035ef6/jobs/14198 . Besides that I think it looks good.

**Comment by theadammurphy** [comment]
Could you please add an explanation for `number_time_series`?

**Comment by isaacmg** [comment]
@theadammurphy That is the total number of time series present (e.g. n_feature_time_series + n_targets)

**Review by isaacmg — APPROVED** [review]
Okay now it is good. wee

**Review by isaacmg — APPROVED** [review]
The rest of unit tests should pass.

**Comment by isaacmg** [comment]
I'll go ahead and merge

**Pull request merged**
