### PR TITLE
'probabalistic dnn'

### PR DESCRIPTION
**Pull request by kritim13**
Branch for the probabilistic dnn model. Added loss function.

### CODE REVIEW

**Comment by isaacmg** [comment]
Could you clarify what `docs/requirements.txt` does and how it is different from the standard `requirements.txt`? I do want to get the unit tests passing and I think that might be why it is failing.

**Comment by kritim13** [comment]
I don't think there is any operational difference between the two requirements.txt files - they both load the required packages. The only advantage of keeping the requirements.txt file in the docs directory is that is helps  ReadTheDocs find the same for the build easily. Let me see if I can use only one requirements.txt file and still have a successful build.

**Comment by isaacmg** [comment]
@kritim13 Can I close this PR due to overlap.

**Comment by kritim13** [comment]
@isaacmg yes, sure

**Pull request closed without merging**
